### ISSUE TITLE
Changing text colour of navbar items

### ISSUE THREAD

**Issue by ronneylogs** [moulibheemaneti/adaptive_navbar#3]
I was wondering how can I style the text of the navbar items.

**Comment by moulibheemaneti** [comment]
> I was wondering how can I style the text of the navbar items.

Hi, @ronneylogs I was inactive for quite a while, so sorry for the delayed response.
Coming to your question, there are a `backgroundColor` and `foregroundColor` options in the Adaptive navbar itself. And the icons in it can be changed with `iconTheme` and `actionsIconTheme`. 

Let me know whether this helps you or not. If not kindly describe your problem in detail.
